version: '3.9'

services:
  server:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: nest-fastify-dev
   ports:
     - '3000:3000'
   depends_on:
     - database
     - cache
   environment:
     REDIS_HOST: 'cache'
     DATABASE_HOST: 'database'
   volumes:
     - server:/app

networks:
  database:
    driver: bridge

volumes:
  database:
  cache:
  server:
