version: '3.9'

services:
  cache:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  server:
    build:
      context: .
      args:
        - PROD=true
      dockerfile: Dockerfile
    container_name: nest-fastify
    environment:
      REDIS_HOST: 'cache'
      DATABASE_HOST: 'database'
    ports:
      - '3000:3000'
    depends_on:
      - cache
    volumes:
      - server:/app
    command: npm run start:prod

networks:
  database:
    driver: bridge

volumes:
  database:
  cache:
  server:
