version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    restart: always

  cache:
    image: redis:latest
    ports:
      - 6379:6379

  server:
    build:
      context: .
      args:
        - ENV=.test
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
      - cache
    command: npm run start:prod
