---
name: Checks

on:
  push:
    branches:
      - 'master'

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    services:
      database:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: ari
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        run: docker-compose -f docker-test.yml build
      - name: Migration Database
        run: docker-compose -f docker-test.yml run --rm server sh -c "npm run migration"
      - name: Lint
        run: docker-compose -f docker-test.yml run --rm server sh -c "npm run lint"

