---
name: Checks

on:
  push:
    branches:
      - 'master'

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:latest
        env:
          POSTGRES_USER: ${DATABASE_USER}
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
          POSTGRES_DB: ${DATABASE_NAME}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run actions/checkout@v2
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose -f docker-test.yml up -d
      - name: Lint
        run: docker-compose -f docker-test.yml run --rm server sh -c "npm run lint"
      - name: Check running containers
        run: docker ps -a
      - name: Migration Database
        run: docker-compose -f docker-test.yml run --rm server sh -c "npm run migration"
